Header header

# Name of the camera
string name

# Timestamp when the camera was opened
time startupTime

# Indicate whether a camera is a master camera
bool isMaster

# Topic name for synchronization service server
string syncServiceTopic

# Indicate whether node is publishing events
bool publishingEvents

# Indicate whether node is publishing frames
bool publishingFrames

# Indicate whether node is publishing IMU data
bool publishingImu

# Indicate whether node is publishing triggers
bool publishingTriggers
