// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_D_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();
}

void import_D_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 1 > >::register_converter();
}

void import_D_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 2 > >::register_converter();
}

void import_D_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 3 > >::register_converter();
}

void import_D_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 4 > >::register_converter();
}

void import_D_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 5 > >::register_converter();
}

void import_D_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, Eigen::Dynamic, 6 > >::register_converter();
}

void import_1_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, Eigen::Dynamic > >::register_converter();
}

void import_1_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 1 > >::register_converter();
}

void import_1_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 2 > >::register_converter();
}

void import_1_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 3 > >::register_converter();
}

void import_1_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 4 > >::register_converter();
}

void import_1_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 5 > >::register_converter();
}

void import_1_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 1, 6 > >::register_converter();
}

void import_2_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, Eigen::Dynamic > >::register_converter();
}

void import_2_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 1 > >::register_converter();
}

void import_2_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 2 > >::register_converter();
}

void import_2_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 3 > >::register_converter();
}

void import_2_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 4 > >::register_converter();
}

void import_2_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 5 > >::register_converter();
}

void import_2_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 2, 6 > >::register_converter();
}

void import_3_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, Eigen::Dynamic > >::register_converter();
}

void import_3_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 1 > >::register_converter();
}

void import_3_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 2 > >::register_converter();
}

void import_3_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 3 > >::register_converter();
}

void import_3_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 4 > >::register_converter();
}

void import_3_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 5 > >::register_converter();
}

void import_3_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 3, 6 > >::register_converter();
}

void import_4_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, Eigen::Dynamic > >::register_converter();
}

void import_4_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 1 > >::register_converter();
}

void import_4_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 2 > >::register_converter();
}

void import_4_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 3 > >::register_converter();
}

void import_4_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 4 > >::register_converter();
}

void import_4_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 5 > >::register_converter();
}

void import_4_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 4, 6 > >::register_converter();
}

void import_5_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, Eigen::Dynamic > >::register_converter();
}

void import_5_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 1 > >::register_converter();
}

void import_5_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 2 > >::register_converter();
}

void import_5_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 3 > >::register_converter();
}

void import_5_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 4 > >::register_converter();
}

void import_5_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 5 > >::register_converter();
}

void import_5_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 5, 6 > >::register_converter();
}

void import_6_D_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, Eigen::Dynamic > >::register_converter();
}

void import_6_1_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 1 > >::register_converter();
}

void import_6_2_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 2 > >::register_converter();
}

void import_6_3_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 3 > >::register_converter();
}

void import_6_4_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 4 > >::register_converter();
}

void import_6_5_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 5 > >::register_converter();
}

void import_6_6_int()
{
	NumpyEigenConverter<Eigen::Matrix< int, 6, 6 > >::register_converter();
}

