// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_D_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();
}

void import_D_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 1 > >::register_converter();
}

void import_D_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 2 > >::register_converter();
}

void import_D_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 3 > >::register_converter();
}

void import_D_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 4 > >::register_converter();
}

void import_D_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 5 > >::register_converter();
}

void import_D_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, Eigen::Dynamic, 6 > >::register_converter();
}

void import_1_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, Eigen::Dynamic > >::register_converter();
}

void import_1_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 1 > >::register_converter();
}

void import_1_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 2 > >::register_converter();
}

void import_1_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 3 > >::register_converter();
}

void import_1_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 4 > >::register_converter();
}

void import_1_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 5 > >::register_converter();
}

void import_1_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 1, 6 > >::register_converter();
}

void import_2_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, Eigen::Dynamic > >::register_converter();
}

void import_2_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 1 > >::register_converter();
}

void import_2_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 2 > >::register_converter();
}

void import_2_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 3 > >::register_converter();
}

void import_2_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 4 > >::register_converter();
}

void import_2_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 5 > >::register_converter();
}

void import_2_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 2, 6 > >::register_converter();
}

void import_3_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, Eigen::Dynamic > >::register_converter();
}

void import_3_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 1 > >::register_converter();
}

void import_3_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 2 > >::register_converter();
}

void import_3_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 3 > >::register_converter();
}

void import_3_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 4 > >::register_converter();
}

void import_3_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 5 > >::register_converter();
}

void import_3_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 3, 6 > >::register_converter();
}

void import_4_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, Eigen::Dynamic > >::register_converter();
}

void import_4_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 1 > >::register_converter();
}

void import_4_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 2 > >::register_converter();
}

void import_4_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 3 > >::register_converter();
}

void import_4_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 4 > >::register_converter();
}

void import_4_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 5 > >::register_converter();
}

void import_4_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 4, 6 > >::register_converter();
}

void import_5_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, Eigen::Dynamic > >::register_converter();
}

void import_5_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 1 > >::register_converter();
}

void import_5_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 2 > >::register_converter();
}

void import_5_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 3 > >::register_converter();
}

void import_5_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 4 > >::register_converter();
}

void import_5_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 5 > >::register_converter();
}

void import_5_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 5, 6 > >::register_converter();
}

void import_6_D_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, Eigen::Dynamic > >::register_converter();
}

void import_6_1_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 1 > >::register_converter();
}

void import_6_2_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 2 > >::register_converter();
}

void import_6_3_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 3 > >::register_converter();
}

void import_6_4_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 4 > >::register_converter();
}

void import_6_5_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 5 > >::register_converter();
}

void import_6_6_uchar()
{
	NumpyEigenConverter<Eigen::Matrix< boost::uint8_t, 6, 6 > >::register_converter();
}

