// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_D_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();
}

void import_D_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 1 > >::register_converter();
}

void import_D_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 2 > >::register_converter();
}

void import_D_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 3 > >::register_converter();
}

void import_D_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 4 > >::register_converter();
}

void import_D_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 5 > >::register_converter();
}

void import_D_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, Eigen::Dynamic, 6 > >::register_converter();
}

void import_1_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, Eigen::Dynamic > >::register_converter();
}

void import_1_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 1 > >::register_converter();
}

void import_1_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 2 > >::register_converter();
}

void import_1_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 3 > >::register_converter();
}

void import_1_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 4 > >::register_converter();
}

void import_1_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 5 > >::register_converter();
}

void import_1_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 1, 6 > >::register_converter();
}

void import_2_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, Eigen::Dynamic > >::register_converter();
}

void import_2_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 1 > >::register_converter();
}

void import_2_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 2 > >::register_converter();
}

void import_2_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 3 > >::register_converter();
}

void import_2_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 4 > >::register_converter();
}

void import_2_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 5 > >::register_converter();
}

void import_2_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 2, 6 > >::register_converter();
}

void import_3_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, Eigen::Dynamic > >::register_converter();
}

void import_3_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 1 > >::register_converter();
}

void import_3_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 2 > >::register_converter();
}

void import_3_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 3 > >::register_converter();
}

void import_3_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 4 > >::register_converter();
}

void import_3_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 5 > >::register_converter();
}

void import_3_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 3, 6 > >::register_converter();
}

void import_4_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, Eigen::Dynamic > >::register_converter();
}

void import_4_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 1 > >::register_converter();
}

void import_4_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 2 > >::register_converter();
}

void import_4_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 3 > >::register_converter();
}

void import_4_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 4 > >::register_converter();
}

void import_4_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 5 > >::register_converter();
}

void import_4_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 4, 6 > >::register_converter();
}

void import_5_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, Eigen::Dynamic > >::register_converter();
}

void import_5_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 1 > >::register_converter();
}

void import_5_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 2 > >::register_converter();
}

void import_5_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 3 > >::register_converter();
}

void import_5_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 4 > >::register_converter();
}

void import_5_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 5 > >::register_converter();
}

void import_5_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 5, 6 > >::register_converter();
}

void import_6_D_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, Eigen::Dynamic > >::register_converter();
}

void import_6_1_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 1 > >::register_converter();
}

void import_6_2_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 2 > >::register_converter();
}

void import_6_3_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 3 > >::register_converter();
}

void import_6_4_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 4 > >::register_converter();
}

void import_6_5_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 5 > >::register_converter();
}

void import_6_6_float()
{
	NumpyEigenConverter<Eigen::Matrix< float, 6, 6 > >::register_converter();
}

