// This file automatically generated by create_export_module.py
#define NO_IMPORT_ARRAY 

#include <NumpyEigenConverter.hpp>

#include <boost/cstdint.hpp>


void import_D_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic > >::register_converter();
}

void import_D_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 1 > >::register_converter();
}

void import_D_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 2 > >::register_converter();
}

void import_D_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 3 > >::register_converter();
}

void import_D_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 4 > >::register_converter();
}

void import_D_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 5 > >::register_converter();
}

void import_D_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, Eigen::Dynamic, 6 > >::register_converter();
}

void import_1_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, Eigen::Dynamic > >::register_converter();
}

void import_1_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 1 > >::register_converter();
}

void import_1_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 2 > >::register_converter();
}

void import_1_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 3 > >::register_converter();
}

void import_1_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 4 > >::register_converter();
}

void import_1_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 5 > >::register_converter();
}

void import_1_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 1, 6 > >::register_converter();
}

void import_2_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, Eigen::Dynamic > >::register_converter();
}

void import_2_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 1 > >::register_converter();
}

void import_2_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 2 > >::register_converter();
}

void import_2_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 3 > >::register_converter();
}

void import_2_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 4 > >::register_converter();
}

void import_2_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 5 > >::register_converter();
}

void import_2_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 2, 6 > >::register_converter();
}

void import_3_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, Eigen::Dynamic > >::register_converter();
}

void import_3_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 1 > >::register_converter();
}

void import_3_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 2 > >::register_converter();
}

void import_3_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 3 > >::register_converter();
}

void import_3_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 4 > >::register_converter();
}

void import_3_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 5 > >::register_converter();
}

void import_3_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 3, 6 > >::register_converter();
}

void import_4_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, Eigen::Dynamic > >::register_converter();
}

void import_4_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 1 > >::register_converter();
}

void import_4_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 2 > >::register_converter();
}

void import_4_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 3 > >::register_converter();
}

void import_4_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 4 > >::register_converter();
}

void import_4_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 5 > >::register_converter();
}

void import_4_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 4, 6 > >::register_converter();
}

void import_5_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, Eigen::Dynamic > >::register_converter();
}

void import_5_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 1 > >::register_converter();
}

void import_5_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 2 > >::register_converter();
}

void import_5_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 3 > >::register_converter();
}

void import_5_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 4 > >::register_converter();
}

void import_5_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 5 > >::register_converter();
}

void import_5_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 5, 6 > >::register_converter();
}

void import_6_D_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, Eigen::Dynamic > >::register_converter();
}

void import_6_1_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 1 > >::register_converter();
}

void import_6_2_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 2 > >::register_converter();
}

void import_6_3_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 3 > >::register_converter();
}

void import_6_4_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 4 > >::register_converter();
}

void import_6_5_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 5 > >::register_converter();
}

void import_6_6_double()
{
	NumpyEigenConverter<Eigen::Matrix< double, 6, 6 > >::register_converter();
}

